In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
#7.1 creates 2 by 3 array with ones
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [3]:
# 3 by 4 array with zeroes
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
# The expression np.full((2, 5), 7) creates a NumPy array of shape (2, 5) (2 rows and 5 columns) filled with the value 7.
np.full((2,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [5]:
# array of evenly spaced values within a given range. Specifically, np.arange(4) generates an array containing integers from 0 to 3.
np.arange(4)

array([0, 1, 2, 3])

In [6]:
# np.arange(0, 4) generates the array The .reshape(2, 2) method then reshapes this 1D array into a 2D array with 2 rows and 2 columns.
np.arange(0,4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [7]:
#The expression np.arange(4).reshape(2, 2)**3 first creates an array using np.arange(4), 
#reshapes it into a 2x2 matrix, and then raises each element of that matrix to the power of 3.
np.arange(4).reshape(2,2)**3

array([[ 0,  1],
       [ 8, 27]], dtype=int32)

In [8]:
#The expression np.arange(4).reshape(2, 2)**3 first creates an array using np.arange(4), 
#reshapes it into a 2x2 matrix, and then adds each element of that matrix plus 7.
np.arange(4).reshape(2,2)+7

array([[ 7,  8],
       [ 9, 10]])

In [9]:
#The expression np.arange(4).reshape(2, 2)**3 first creates an array using np.arange(4), 
#reshapes it into a 2x2 matrix, and then multiplies each element of that matrix by 2.
np.arange(4).reshape(2,2)*2

array([[0, 2],
       [4, 6]])

In [10]:
#7.3 The expression a = np.arange(2, 19, 2).reshape(3, 3) 
#creates a NumPy array with specific values and reshapes it into a 3x3 matrix. 
a = np.arange(2,19,2).reshape(3,3)

In [11]:
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [12]:
#The expression b = np.arange(9, 0, -1).reshape(3, 3) creates a NumPy array that counts down from 9 to 1 and reshapes it into a 3x3 matrix. 
b = np.arange(9,0,-1).reshape(3,3)

In [13]:
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [14]:
#Given the matrices a and b as defined earlier, performing the operation a * b will result in element-wise multiplication.
a*b

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

In [15]:
#7.4 create 3 by 3 array even int 2 through 18 second array and multiply both arrays[16]
import numpy as np

# Create the first array of even integers from 2 to 18
array_1 = np.arange(2, 19, 2).reshape(3, 3)

# Create the second array filled with 16s
array_2 = np.full((3, 3), 16)

# Multiply both arrays
result = array_1 * array_2

print("Array 1:")
print(array_1)
print("\nArray 2:")
print(array_2)
print("\nResult of multiplication:")
print(result)


Array 1:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Array 2:
[[16 16 16]
 [16 16 16]
 [16 16 16]]

Result of multiplication:
[[ 32  64  96]
 [128 160 192]
 [224 256 288]]


In [16]:
#7.5 flattening arrays with flatten vs. ravel
#2 by 3 array containing the first six powers of 2
d=2**np.arange(6).reshape(2,3)
d

array([[ 1,  2,  4],
       [ 8, 16, 32]], dtype=int32)

In [17]:
#The expression e = d.flatten() takes the 2D array d and converts it into a 1D array.
e=d.flatten()

In [18]:
e

array([ 1,  2,  4,  8, 16, 32], dtype=int32)

In [19]:
#d array has not been changed
d

array([[ 1,  2,  4],
       [ 8, 16, 32]], dtype=int32)

In [20]:
#The expression f = d.ravel() also converts the 2D array d into a 1D array, similar to flatten().
#However, ravel() returns a flattened array that is a view of the original array whenever possible, 
#meaning it may not create a copy of the data if not necessary.
f=d.ravel()
f

array([ 1,  2,  4,  8, 16, 32], dtype=int32)

In [21]:
d

array([[ 1,  2,  4],
       [ 8, 16, 32]], dtype=int32)

In [22]:
#7.6The expression g = np.linspace(1.1, 6.6, num=6).reshape(2, 3) 
#creates an array with evenly spaced values between 1.1 and 6.6, 
# and then reshapes it into a 2x3 matrix. 
g=np.linspace(1.1,6.6,num=6).reshape(2,3)

In [23]:
g

array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6]])

In [24]:
#The expression df = g.astype(int) converts the elements of the array g to integers
df=g.astype(int)

In [25]:
df

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#7.9 The expression h = np.arange(1, 16).reshape(3, 5) creates a NumPy array with integers ranging from 1 to 15 and reshapes it into a 3x5 matrix.
h=np.arange(1,16).reshape(3,5)
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
#The expression h[1] accesses the second row of the array h.
h[1]

array([ 6,  7,  8,  9, 10])

In [28]:
#The expression h[:, 4] accesses all rows of the 5th column (index 4) in the array h
h[:, 4]

array([ 5, 10, 15])

In [29]:
#rows 0 and 1
h[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
#d columns 2-4
h[:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [31]:
#e element in row 1 and column 4
h[1,4]

10

In [32]:
h[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
#The overall effect of this code is to create a new array that includes all elements from a whose rows are not present in b,
#flattened into a 1D array and then reshaped into the original number of columns from a.
delta = set(map(tuple, b))
np.fromiter((x for xs in a if tuple(xs) not in delta for x in xs), dtype=a.dtype).reshape(-1, a.shape[-1])


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [34]:
#creates two NumPy arrays, array1 and array2, and then attempts to vertically stack them and reshape the result.

In [35]:
array1 = np.array([[0,1], [2,3]])
array1

array([[0, 1],
       [2, 3]])

In [36]:
array2 = np.array([[4,5], [6,7]])
array2

array([[4, 5],
       [6, 7]])

In [37]:
array3 =np.vstack((array1, array2)).reshape(2,4)
array3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
array4 = np.hstack((array1, array2)).reshape(2,4)

In [39]:
array4

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [40]:
array5= np.vstack(array4*2)

In [41]:
array5

array([[ 0,  2,  8, 10],
       [ 4,  6, 12, 14]])

In [42]:
#a
number = pd.Series([7,11,13,17])

In [43]:
number

0     7
1    11
2    13
3    17
dtype: int64

In [44]:
#The line of code you provided creates a Pandas Series named number with the values [7, 11, 13, 17].
#The pd.Series constructor takes a list (or other iterable) as input and creates a Series object.
n = pd.Series(100, range(5))

In [45]:
n

0    100
1    100
2    100
3    100
4    100
dtype: int64

In [46]:
#Importing the random Module: You need to import the random module to use its functions.
#Generating the Range: range(0, 101) creates an iterable of numbers from 0 to 100 (inclusive).
#Sampling: random.sample(range(0, 101), 20) randomly selects 20 unique integers from this range. 
#Since the sample size is 20, it will select without replacement, meaning no number will appear more than once in the list.
num= random.sample(range(0,101), 20)

In [47]:
num

[59, 20, 62, 85, 34, 14, 36, 86, 1, 56, 57, 4, 77, 18, 88, 58, 16, 25, 24, 9]

In [48]:
#numb.describe(), computes and returns the following summary statistics:
numb = pd.Series(num)
numb.describe()

count    20.000000
mean     41.450000
std      28.958182
min       1.000000
25%      17.500000
50%      35.000000
75%      59.750000
max      88.000000
dtype: float64

In [49]:
#creates a Pandas Series named temperatures with specific temperature values, 
#each associated with an index label representing a person's name.
temperatures = pd.Series([98.6,98.9,100.2,97.9], index=['Julie', 'Charlie', 'Sam', 'Andrea'])

In [50]:
temperatures

Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64

In [51]:
#The line of code dict = temperatures.to_dict() converts the Pandas Series temperatures into a Python dictionary.
dict= temperatures.to_dict()

In [52]:
dict

{'Julie': 98.6, 'Charlie': 98.9, 'Sam': 100.2, 'Andrea': 97.9}

In [53]:
#The line of code pd.DataFrame(dict, index=['TEMP']) attempts to create a Pandas DataFrame 
#from the dictionary created from the temperatures Series. 
pd.DataFrame(dict, index=['TEMP'])

Julie  Charlie    Sam  Andrea
TEMP   98.6     98.9  100.2    97.9

In [54]:
#The line of code provided creates a dictionary named temperature that holds lists of temperature readings for different individuals. 
temperature = {'Maxine': [96.8, 97, 99], 'James': [97.2, 98.3, 100.3], 'Amanda': [97.4,98.2,99.2]}
temperature

{'Maxine': [96.8, 97, 99],
 'James': [97.2, 98.3, 100.3],
 'Amanda': [97.4, 98.2, 99.2]}

In [55]:
#The line of code time = pd.DataFrame(temperature, index=['Morning', 'Afternoon', 'Evening']) 
#creates a Pandas DataFrame from the temperature dictionary you defined earlier.
time = pd.DataFrame(temperature, index=['Morning', 'Afternoon', 'Evening'])

In [56]:
time

Maxine  James  Amanda
Morning      96.8   97.2    97.4
Afternoon    97.0   98.3    98.2
Evening      99.0  100.3    99.2

In [57]:
#cThe expression time['Maxine'] accesses the column in the DataFrame time corresponding to the key 'Maxine'. 
#Given the DataFrame created from the temperature dictionary, 
#this will return the temperature readings for Maxine at different times of the day.
time['Maxine']

Morning      96.8
Afternoon    97.0
Evening      99.0
Name: Maxine, dtype: float64

In [58]:
#The expression time[0:1] is used to slice the DataFrame time to select the first row (or rows) based on its positional index.
time[0:1]

Maxine  James  Amanda
Morning    96.8   97.2    97.4

In [59]:
#The expression time[0:3:2] slices the DataFrame time using the positional index, selecting rows from index 0 to 3 with a step of 2.
time[0:3:2]

Maxine  James  Amanda
Morning    96.8   97.2    97.4
Evening    99.0  100.3    99.2

In [60]:
#The expression time.loc['Morning':'Evening', ['Maxine', 'Amanda']] 
#is used to select specific rows and columns from the DataFrame time based on labels.
time.loc['Morning':'Evening', ['Maxine', 'Amanda']]

Maxine  Amanda
Morning      96.8    97.4
Afternoon    97.0    98.2
Evening      99.0    99.2

In [61]:
#same 
time.loc['Morning':'Afternoon', ['Maxine', 'Amanda']]

Maxine  Amanda
Morning      96.8    97.4
Afternoon    97.0    98.2

In [62]:
#h
time.describe()

Maxine       James     Amanda
count   3.000000    3.000000   3.000000
mean   97.600000   98.600000  98.266667
std     1.216553    1.571623   0.901850
min    96.800000   97.200000  97.400000
25%    96.900000   97.750000  97.800000
50%    97.000000   98.300000  98.200000
75%    98.000000   99.300000  98.700000
max    99.000000  100.300000  99.200000

In [63]:
#The line of code temperature = time.transpose() transposes the DataFrame time, switching its rows and columns. 
temperature = time.transpose()

In [64]:
temperature

Morning  Afternoon  Evening
Maxine     96.8       97.0     99.0
James      97.2       98.3    100.3
Amanda     97.4       98.2     99.2

In [65]:
#The expression temperature[2::-1] is used to slice the DataFrame (or Series) temperature based on positional indexing.
#Slicing Explained[2::] This indicates the starting position of the slice. In the context of a DataFrame, this references the third row 
#(if there are at least three rows).::-1: This specifies a step of -1, meaning you want to reverse the order of the rows starting 
#from the index 2 down to the beginning (index 0).
temperature[2::-1]
            

Morning  Afternoon  Evening
Amanda     97.4       98.2     99.2
James      97.2       98.3    100.3
Maxine     96.8       97.0     99.0